[package]
name = "hv-ctl"
version = "0.1.0"
authors = ["bunnie"]

[dependencies]
cupi = { path = "../cupi" }
cupi_shift = { path = "../cupi_shift" }
libc = "*"
quick-error = "*"
enum_primitive = "*"
num = "*"
spidev = "*"
text_io = "*"
websocket = "*"
rand = "*"
